# Define on 20200803 to initialize 3 node kubernetes cluster
# 

Vagrant.configure("2") do |config|
  # Define image
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  # Define nfs8server, provision using automatic installation script
  config.vm.define "nfs8server", autostart: false do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "nfs8server"
      vb.memory = 1024
      vb.cpus = 1
    end
    node.vm.hostname = "nfs8server"
    node.vm.network "private_network", ip: "192.168.56.50"  
    node.vm.network "forwarded_port", guest: 22, host: "5022", auto_correct: true
    node.vm.provision :shell, :path => "hosts_install.sh"
    node.vm.provision :shell, :path => "nfs-server-install.sh"
  end

  # Define nfs8client, provision using automatic installation script
  config.vm.define "nfs8client", autostart: true do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "nfs8client"
      vb.memory = 1024
      vb.cpus = 1
    end
    node.vm.hostname = "nfs8client"
    node.vm.network "private_network", ip: "192.168.56.51"  
    node.vm.network "forwarded_port", guest: 22, host: "5122", auto_correct: true
    node.vm.provision :shell, :path => "hosts_install.sh"
    node.vm.provision :shell, :path => "nfs-client-install.sh"
  end

end
