apiVersion: v1
kind: Pod
metadata:
  name: app-node
  labels:
    app: ogl-app
spec:
  containers:
    - name: ogl-application
      image: app-node
      command: ['sh','-c','echo Hello Kubernetes! ']
      resources:
        requests:
          cpu: "64Mi"
          memory: "250m"
        limits:
          cpu: "128Mi"
          memory: "500m"