apiVersion: v1
kind: Pod
metadata:
  name: app-node2
  labels:
    app: ogl-app
spec:
  containers:
    - name: ogl-application
      image: web-node
      command: ['sh','-c','echo Hello Kubernetes! ']
      resources:
        requests:
          cpu: "1024Mi"
          memory: "500m"
        limits:
          cpu: "2048Mi"
          memory: "1024m"