# Define on 20200803 to initialize 3 node kubernetes cluster
# 

Vagrant.configure("2") do |config|
  # Define image
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  # Define nfs8server, provision using automatic installation script
  config.vm.define "k8nfs", autostart: false do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8nfs"
      vb.memory = 1024
      vb.cpus = 1
    end
    node.vm.hostname = "k8nfs"
    node.vm.network "private_network", ip: "192.168.56.50"  
    node.vm.network "forwarded_port", guest: 22, host: "5022", auto_correct: true
    node.vm.provision :shell, :path => "hosts_install.sh"
    node.vm.provision :shell, :path => "nfs-server-install.sh"
  end

# Define k8m, provision using automatic installation script
  config.vm.define "k8m", autostart: true do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8m"
      vb.memory = 4096
      vb.cpus = 2
    end
    node.vm.hostname = "k8m"
    node.vm.network "private_network", ip: "192.168.56.53"  
    node.vm.network "forwarded_port", guest: 22, host: "5322", auto_correct: true
    node.vm.provision :shell, :path => "hosts_install.sh"
    node.vm.provision :shell, :path => "k18-docker-install.sh"
    node.vm.provision :shell, :path => "k18-kube-software-install.sh"
    node.vm.provision :shell, :path => "nfs-client-install.sh"
  end

# Define k8worker1, provision using automatic installation script
  config.vm.define "k8w1", autostart: true do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8w1"
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.hostname = "k8w1"
    node.vm.network "private_network", ip: "192.168.56.54"  
    node.vm.network "forwarded_port", guest: 22, host: "5422", auto_correct: true
    node.vm.provision :shell, :path => "hosts_install.sh"
    node.vm.provision :shell, :path => "k18-docker-install.sh"
    node.vm.provision :shell, :path => "k18-kube-software-install.sh"
    node.vm.provision :shell, :path => "nfs-client-install.sh"
  end


# Define k8w2, provision using automatic installation script
  config.vm.define "k8w2", autostart: false do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8w2"
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.hostname = "k8w2"
    node.vm.network "private_network", ip: "192.168.56.55"
    node.vm.network "forwarded_port", guest: 22, host: "5522", auto_correct: true
    node.vm.provision :shell, :path => "hosts_install.sh"
    node.vm.provision :shell, :path => "k18-docker-install.sh"
    node.vm.provision :shell, :path => "k18-kube-software-install.sh"
    node.vm.provision :shell, :path => "nfs-client-install.sh"
  end



end
