apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.15.8
    livenessProbe:
       httpGet:
         path: /
         port: 80
