apiVersion: v1
kind: Pod
metadata:
  name: my-production-label-pod
  labels:
    app: my-app
    environment: production
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh','-c','echo Hello, Kubernetes! && sleep 3600']