apiVersion: v1
kind: Pod
metadata:
  name: pod-node2-ng
  labels:
    type: front-end
spec:
  containers:
    - name: nginx-proxy
      image: nginx
      ports:
       - containerPort: 8080
  nodeName: kube-node2

