apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    name: replica
    tier: frontend
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        type: front-end
    spec:
      containers:
        - name: nginx-proxy
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
