apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
  labels:
    app: dev-rc-nginx
    type: frontend
spec:
  replicas: 3
  templates:
    metadata:
      name: ng-pod
      labels:
        app: test-pod
        type: webend
    spec:
      containers:
        - name: nginx-proxy
          image: nginx


