apiVersion: v1
kind: ReplicationController
metadata:
  name: rectl-ng
  labels:
    app: testing
    type: frontend
spec:
  templates:
    metadata:
      name: ng-pod
      labels:
        app: test-pod
        type: webend
    spec:
      containers:
        - name: nginx-proxy
          image: nginx
  replicas: 3

