apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    name: nodeport
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
      app: my-app
      type: front-end
  nodeName: node2