apiVersion: v1
kind: Service
metadata:
  name: srv-nginx
  labels:
    name: dev-np-nginx
    tier: dev-service
spec:
  type: NodePort
  ports:
   - targetPort: 80
     port: 80
     nodePort: 30080
  selector:
     type: front-end

