apiVersion: v1
kind: Service
metadata:
  name: ogl-svc-ng
  labels:
    apps: ogl-svc-frontend
    type: frontend
spec:
   type: NodePort
   selector:
      apps: ogl-pod-ng
   ports:
    - nodePort: 32000
      port: 80
      targetPort: 9000
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: ogl-pv-ng
   labels:
      apps: ogl-pv-ng
      type: frontend
spec:
   storageClassName: manual
   capacity:
       storage: 2Gi
   accessModes:
       - ReadWriteOnce
   hostPath:
       path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: ogl-pvc-ng
   labels:
     apps: ogl-pvc-ng
     type: frontend
spec:
   storageClassName: manual
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
        storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: ogl-deploy-ng
   labels:
      apps: ogl-deploy-ng
      type: frontend
spec:
   replicas: 3
   selector:
      matchLabels:
        apps: ogl-pod-ng
   template:
      metadata:
        name: ogl-pod-ng
        labels:
           apps: ogl-pod-ng
           type: frontend
      spec:
        volumes:
           - name: ogl-pvm-ng
             persistentVolumeClaim:
                claimName: ogl-pvc-ng
        containers:
          - name: ogl-con-ng
            image: nginx
            ports:
              - containerPort: 80
            volumeMounts:
              - mountPath: "/etc/nginx/conf.d/"
                name: ogl-pvm-ng



