apiVersion: v1
kind: PersistentVolume
metadata:
   name: ogl-pv-ng
   labels:
      apps: ogl-pv-ng
      type: frontend
spec:
   storageClassName: manual
   capacity:
       storage: 2Gi
   accessModes:
       - ReadWriteOnce
   hostPath:
       path: '/mnt/data'