apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  serviceAccountName: my-serviceaccount
  securityContext:
    runAsUser: 2000
    fsGroup: 3000
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c, 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
    restartPolicy: Never
    env:
      - name: MY_VAR
        valueFrom:
          configMapKeyRef:
            name: my-config-map
            key: myKey
      - name: MY_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: myKey
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
    ports:
      - containerPort: 80
    livenessProbe:
      exec:
        command:
          - echo
          - testing
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
data:
   myKey: myValue
   anotherKey: anotherValue
stringData:
  myKey: myPasswd
