---
apiVersion: v1
kind: Service
metadata:
  name: odoo-svr
  labels:
    app: odoo-svr
spec:
  ports:
    - port: 8069
  selector:
    app: odoo-svr
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-svr
  labels:
    app: odoo-svr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-svr
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo-svr
        tier: frontend
    spec:
      containers:
        - image: odoo:15.0
          name: odoo
          env:
          - name: HOST
            value: odoo-db
          - name: USER
            value: odoo
          - name: PASSWORD
            value: password
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
          volumeMounts:
          - name: odoo-pvc
            mountPath: /var/lib/odoo
          - name: odoo-addons
            mountPath: /mnt/extra-addons
      volumes:
      - name: odoo-pvc
        persistentVolumeClaim:
          claimName: odoo-pvc
      - name: odoo-addons
        persistentVolumeClaim:
          claimName: odoo-addons
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: addons
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0003/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  labels:
    app: odoo-svr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-addons
  labels:
    app: odoo-svr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi