apiVersion: v1
kind: Service
metadata:
  name: ogl-svc-ng
  labels:
    apps: ogl-svc-frontend
    type: frontend
spec:
   type: NodePort
   selector:
      apps: ogl-pod-ng
   ports:
    - nodePort: 32000
      port: 80
      targetPort: 80