apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: ogl-pvc-ng
   labels:
     apps: ogl-pvc-ng
     type: frontend
spec:
   storageClassName: manual
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
        storage: 1Gi