version: '3'
services:
  web:
      image: nginx
      ports:
      -  "8050:80"
      volumes:
      -  nginx_html:/usr/share/nginx/html/
      links:
      -  redis
  redis:
      image: redis
volumes:
  nginx_html: {}
